"""
GRACE-FO GPS1B RINEX 2.20 loader

RINEX format (generated by gps1x2rnx from JPL RL04 ASCII):
  9 observation types: L1 L2 C1 P1 P2 LA SA S1 S2
  L1, L2: carrier phase in FULL CYCLES (code-aligned, B_if ≈ 0)
  C1, P1, P2: pseudorange in METERS
  LA: L1 phase (alternate), SA/S1/S2: SNR
  LLI (Loss of Lock Indicator) in last digit of each observation field
  10-second interval, GPS time system

Note: Phase is code-aligned by JPL processing — integer ambiguity is removed.
      B_if = L_if - P_if ≈ 0 (within code noise ~0.3m).
"""
import numpy as np
from datetime import datetime, timedelta
from pathlib import Path
import pickle

C = 299792458.0
F1, F2 = 1575.42e6, 1227.60e6
LAM1 = C / F1
LAM2 = C / F2
F1_SQ, F2_SQ = F1 * F1, F2 * F2
ALPHA = F1_SQ / (F1_SQ - F2_SQ)
BETA = -F2_SQ / (F1_SQ - F2_SQ)

GPS_ORIGIN = datetime(1980, 1, 6, 0, 0, 0)

# GPS-UTC leap seconds (for 2024: 18s)
_GPS_UTC_LEAP = 18


def gps_time_to_utc(gps_week, gps_sow):
    """Convert GPS week + seconds-of-week to UTC datetime."""
    gps_seconds = gps_week * 604800 + gps_sow
    utc = GPS_ORIGIN + timedelta(seconds=gps_seconds - _GPS_UTC_LEAP)
    return utc


def _parse_rnx_epoch(line):
    """Parse RINEX epoch header line.
    Returns (utc_dt, n_sat, prn_list, flag) or None.
    """
    try:
        yy = int(line[1:3])
        mm = int(line[4:6])
        dd = int(line[7:9])
        hh = int(line[10:12])
        mi = int(line[13:15])
        ss = int(line[16:18])
        # microseconds
        us_str = line[19:26].strip() if len(line) > 26 else '0'
        us = float(us_str) if us_str else 0.0

        flag = int(line[28:29]) if len(line) > 28 else 0
        n_sat_str = line[29:32].strip()
        n_sat = int(n_sat_str) if n_sat_str else 0

        # PRN list starting at position 32, every 3 chars
        prns = []
        for i in range(n_sat):
            pos = 32 + i * 3
            if pos + 2 < len(line):
                prn_str = line[pos:pos+3].strip()
                if prn_str:
                    prns.append(prn_str)

        # GPS time (no leap second correction needed for RINEX internal consistency)
        # The RINEX header says GPS time system
        dt = datetime(2000 + yy, mm, dd, hh, mi, ss) + timedelta(microseconds=int(us * 1e6))
        # Convert from GPS to UTC
        utc_dt = dt - timedelta(seconds=_GPS_UTC_LEAP)

        return utc_dt, n_sat, prns, flag
    except (ValueError, IndexError):
        return None


def _parse_obs_line(line, n_fields):
    """Parse one line of RINEX observations.
    Each field is up to 16 chars: value (F15.3 area) + LLI (1 char).
    Missing values are blanks.
    Returns list of (value, lli) tuples.
    """
    results = []
    for i in range(n_fields):
        start = i * 16
        end = start + 16
        if start >= len(line):
            results.append((None, 0))
            continue
        field = line[start:end]
        if not field.strip():
            results.append((None, 0))
            continue
        # Last char is LLI
        val_str = field[:-1].strip()
        lli_str = field[-1]
        try:
            val = float(val_str) if val_str else None
            lli = int(lli_str) if lli_str.isdigit() else 0
        except ValueError:
            val = None
            lli = 0
        results.append((val, lli))
    return results


def load_gps1b_rnx(filepath, cache_dir=None):
    """Parse GPS1B RINEX file. Returns {gps_sod: {sv: rec}} with .pkl cache."""
    rnx_path = Path(filepath)
    if not rnx_path.exists():
        print(f"  [ERROR] RINEX not found: {filepath}")
        return None

    # Cache
    if cache_dir is None:
        cache_dir = rnx_path.parent
    cache_path = Path(cache_dir) / (rnx_path.stem + '.pkl')

    if cache_path.exists():
        try:
            gps_obs = pickle.load(open(cache_path, 'rb'))
            n_obs = sum(len(v) for v in gps_obs.values())
            print(f"  [RNX cache] {rnx_path.name}: {len(gps_obs)} epochs, {n_obs} obs")
            return gps_obs
        except Exception:
            pass

    print(f"  [RNX parse] {rnx_path.name}...")
    with open(rnx_path, 'r') as f:
        lines = f.readlines()

    # Find end of header
    hdr_end = 0
    for i, line in enumerate(lines):
        if 'END OF HEADER' in line:
            hdr_end = i + 1
            break

    N_OBS_TYPES = 9  # L1 L2 C1 P1 P2 LA SA S1 S2
    N_FIELDS_LINE1 = min(5, N_OBS_TYPES)
    N_FIELDS_LINE2 = N_OBS_TYPES - N_FIELDS_LINE1

    gps_obs = {}
    i = hdr_end
    n_total = 0

    while i < len(lines):
        line = lines[i].rstrip('\n\r')
        if not line.strip():
            i += 1
            continue

        parsed = _parse_rnx_epoch(line)
        if parsed is None:
            i += 1
            continue

        utc_dt, n_sat, prns, flag = parsed
        gps_sod = int((utc_dt - datetime(2000, 1, 1, 12, 0, 0)).total_seconds() + _GPS_UTC_LEAP)
        i += 1

        epoch_data = {}
        for prn in prns:
            if i >= len(lines):
                break

            sv = f'G{prn}'

            # Line 1: L1, L2, C1, P1, P2
            obs1 = _parse_obs_line(lines[i], N_FIELDS_LINE1)
            i += 1

            # Line 2: LA, SA, S1, S2
            if i < len(lines):
                obs2 = _parse_obs_line(lines[i], N_FIELDS_LINE2)
                i += 1
            else:
                obs2 = [(None, 0)] * N_FIELDS_LINE2

            all_obs = obs1 + obs2
            # Order: L1, L2, C1, P1, P2, LA, SA, S1, S2
            L1_val, L1_lli = all_obs[0]
            L2_val, L2_lli = all_obs[1]
            C1_val, C1_lli = all_obs[2]
            P1_val, P1_lli = all_obs[3]
            P2_val, P2_lli = all_obs[4]

            # Need both phase and pseudorange
            if L1_val is None or L2_val is None:
                continue
            if C1_val is None and P1_val is None:
                continue
            if P2_val is None:
                continue

            P1_use = C1_val if C1_val is not None else P1_val
            C1_use = C1_val if C1_val is not None else P1_val

            # SNR check
            SA_val, _ = all_obs[6] if len(all_obs) > 6 else (None, 0)
            if SA_val is not None and SA_val < 5:
                continue

            # Convert phase: RINEX stores in full cycles
            L1_cyc = L1_val
            L2_cyc = L2_val

            # LLI (cycle slip) flags — bit 0 = loss of lock
            slip_L1 = bool(L1_lli & 1)
            slip_L2 = bool(L2_lli & 1)

            # Compute IF combinations
            L1_m = L1_cyc * LAM1
            L2_m = L2_cyc * LAM2
            L_if = ALPHA * L1_m + BETA * L2_m
            P1_m = P1_use
            P2_m = P2_val
            P_if = ALPHA * P1_m + BETA * P2_m

            epoch_data[sv] = {
                'sv': sv,
                'gps_sod': gps_sod,
                'L1_cyc': L1_cyc,
                'L2_cyc': L2_cyc,
                'P1': P1_m,
                'P2': P2_m,
                'C1': C1_use,
                'P_if': P_if,
                'L_if': L_if,
                'slip_L1': slip_L1,
                'slip_L2': slip_L2,
            }
            n_total += 1

        if epoch_data:
            gps_obs[gps_sod] = epoch_data

    print(f"  [RNX] {n_total} obs in {len(gps_obs)} epochs")
    if gps_obs:
        pickle.dump(gps_obs, open(cache_path, 'wb'))
        print(f"  [cached] {cache_path}")
    return gps_obs
